### ISSUE TITLE
Make a Punk not showing classes

### ISSUE THREAD

**Issue by WildDog26** [fvtt-fria-ligan/cyborg-foundry-vtt#10]
Is there a setting or something that needs to be flipped on?

**Comment by mcglincy** [comment]
The classes from the book are in the CY_BORG Core Content module, which hasn't been made public yet (and will be as soon as the CY book is available for retail). If you're a Kickstarter backer who already has the PDF, you can contact me in the MB discord about early access testing.

**Comment by PedalFast** [comment]
Hey any update on this? I think the official release is nov 15th but i got mine from amazon on the 1st.

**Comment by mcglincy** [comment]
CY_Borg authors asked me to wait to release until the official retail date (November 15th), as they've granted me permission to include a subset of content from the book.

**Comment by PedalFast** [comment]
okay cool thanks for the info.

**Comment by mcglincy** [comment]
I pushed the latest-greatest release to Foundry yesterday, which now includes the classes from the book (so, the "Make Punk" button should work out of the box). Let me know if you hit any problems!
