### ISSUE TITLE
Appears default ui box width is slightly too small

### ISSUE THREAD

**Issue by DoNotResuscitate** [fvtt-fria-ligan/cyborg-foundry-vtt#15]
Seems the default window needs to be expanded a little bit horizontally. The taxi is an example of all newly created actors, while the character I expanded slightly. The HP and inventory buttons are slightly occluded by default. The first image is an example of the width of the expanded character behind the default taxi.

![Screen Shot 2022-11-16 at 21 47 27](https://user-images.githubusercontent.com/33287665/202342594-08a91b48-1a62-4659-ad21-320c53242bcf.png)

![Screen Shot 2022-11-16 at 21 47 35](https://user-images.githubusercontent.com/33287665/202342605-1b4c00d4-a14f-4e15-b480-d692d533847d.png)
![Screen Shot 2022-11-16 at 21 48 59](https://user-images.githubusercontent.com/33287665/202342677-6de88c2e-935f-481a-807d-605a3f364090.png)

**Comment by mcglincy** [comment]
@DoNotResuscitate What OS, browser, and screen resolution is this happening with? It seems like maybe the scrollbar width is encroaching on the rest of the sheet. (fwiw I'm not seeing the same occlusion with macos chrome, and my scrollbar is a different color)

**Comment by DoNotResuscitate** [comment]
This is Mac OS, Firefox, 1440p monitor.

**Comment by mcglincy** [comment]
Fixed in 1.2.2.
