### ISSUE TITLE
Reboot button no longer work

### ISSUE THREAD

**Issue by Nekoan9119** [fvtt-fria-ligan/cyborg-foundry-vtt#35]
![Sans titre](https://github.com/fvtt-fria-ligan/cyborg-foundry-vtt/assets/135512175/cbbcb77d-e3dd-4123-ab99-cf0f0d87828a)

Great job on everything else, the sheet is georgous and work like a charm.

**Comment by mcglincy** [comment]
Thanks for the bug report! I just released version 2.1.1 with a fix.
