### ISSUE TITLE
Compendium image blank

### ISSUE THREAD

**Issue by Nekoan9119** [fvtt-fria-ligan/cyborg-foundry-vtt#37]
"Hey, it's me, your boi"

Anther day, another bug report ! I don't know if this one is from my end or general, but it does seem that folder image get fucked up on Cy_Borg sheet.

![Sans titre](https://github.com/fvtt-fria-ligan/cyborg-foundry-vtt/assets/135512175/5c602fb2-b577-43d1-b323-f4e797ea31b9)

Not game changing or anything, just wanna let you know :)
(I did test it on a new world without any module and it still does the same bug, but Mörk/Grimm doesn't get this one)

As a token of gratitude, here a picture of a cute kitten

![photo-1611267254323-4db7b39c732c](https://github.com/fvtt-fria-ligan/cyborg-foundry-vtt/assets/135512175/5575d57c-a87b-4119-b779-22cf8a19c35b)

**Comment by mcglincy** [comment]
nice kitten! The folder image is actually changed on purpose (by me) with some custom CSS, as it was driving me insane when trying to organize the compendiums. I can revert that and let the Foundry stock images show, though. (esp. as I don't have a cool CY-ish replacement image atm).

**Comment by mcglincy** [comment]
hmmm
![Screenshot 2023-06-10 at 7 13 06 AM](https://github.com/fvtt-fria-ligan/cyborg-foundry-vtt/assets/189172/e2ab3038-c154-4920-9368-8fbaf5ac1b59)

**Comment by mcglincy** [comment]
Fixed in new 2.2.0 release.
